# -*- coding: utf-8 -*-
"""day3_conditional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f9LNfyXMbsuC_bCtFM5a3cPBrHUWqtQX
"""

n=int(input().strip())
1<n<100

def conditional():
  if n%2==1:
    print('Weird')
  elif 2<n<5:
     print('Not Weird')
  elif n<20:
     print('Weird')
  else:
    print('Not Weird')
  

conditional()

