# -*- coding: utf-8 -*-
"""HackerRank Day 1: Data Types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYR4u5pZNfo1ygJ_xe3Ad6A3-SeSAsOj
"""

i = 4
d = 4.0
s = 'HackerRank '


# Read and save an integer, double, and String to your variables.
integer = int(input())
double = float (input())
string = str(input())

# Print the sum of both integer variables on a new line.
print (i+integer)
# Print the sum of the double variables on a new line.
print (d+double)
# Concatenate and print the String variables on a new line
print(s+string)
# The 's' variable above should be printed first.

